### ISSUE TITLE
Fetch checking account transactions

### ISSUE THREAD

**Issue by MadeInPierre** [lasconic/finary_uapi#119]
Hello!

J'aurais préféré t'envoyer une PR directement, mais looks like I'm stuck...

J'aimerais récupérer les nouvelles transactions dispo sur Finary, mon navigateur utilise l'URL suivante : 

```
https://api.finary.com/organizations/***/users/***/portfolio/checking_accounts/transactions?page=1&per_page=50&institution_id=***
```

J'ai donc essayé de créer un nouveau fichier `user_transactions.py` dans `finary_uapi` en prenant les valeurs utilisées par le call dans le navigateur : 

```python
import json
import logging
import requests

from .constants import API_ROOT

def get_transactions_from_account_id(
        session: requests.Session, 
        organization_id: str, 
        user_id: str, 
        institution_id: str, 
        page: int = 1, 
        per_page: int = 50,
    ):
    url = f"{API_ROOT}/organizations/{organization_id}/users/{user_id}/portfolio/checking_accounts/transactions?{page=}&{per_page=}&{institution_id=}"
    x = session.get(url, params={})
    logging.debug(json.dumps(x.json(), indent=4))
    return x.json()
```

Mais je récupère une réponse vide, alors que le navigateur reçoit bien la liste de transactions : 

```python
{'result': [], 'message': 'OK', 'error': None}
```

J'ai une session valide juste avant le call. Any ideas? :pray:

**Comment by lasconic** [comment]
I'll have a look. I didn't know about this new feature. Neat. Hope it stills work with the /me URLs scheme...

**Comment by MadeInPierre** [comment]
I tried it without luck, hopefully you'll find something

**Comment by lasconic** [comment]
It does work with /users/me and it could be that you forgot the page and per_page param ? if I remove them I have a empty answer. Give me some more minutes and I will push an (untested) update

**Comment by lasconic** [comment]
It's in in version 0.1.6 on pypi and it should be working. The command line tool in __main__ doesn't expose all the options but the function in `user_portfolio.py` supports page, per_page, query (to filter transactions) and institution_id (to filter by banks)

**Comment by lasconic** [comment]
Note: I don't have a credit card in finary. So it works only for checking_accounts so far. If there are other calls, feel free to make another PR.
