### ISSUE TITLE
Fetch credit card transactions ?

### ISSUE THREAD

**Issue by lasconic** [lasconic/finary_uapi#128]
I would need some help here since I can't test and I don't know the URL for credit cards. Maybe it works already ?

**Comment by nmathey** [comment]
Hi,

I can help ;)
[...]/portfolio/credit_accounts?period=1y
[...]/portfolio/credit_accounts/transactions?page=1&per_page=50

looks like same response format than normal bank account but let's test

**Comment by lasconic** [comment]
Do you write the code or I do ?

**Comment by lasconic** [comment]
`[...]/portfolio/credit_accounts/transactions?page=1&per_page=50`

Can it take account_id and institution_id as parameter as well ? If it does, it can use the same function than the other two, `get_portfolio_transactions`

**Comment by nmathey** [comment]
> Do you write the code or I do ?

I can do it I guess ;)
I'll let you know how it goes.

**Comment by lasconic** [comment]
About the response format... this project doesn' really assume much about the response format and let the users (finalynx, you etc...). It would be great to document the response format and I started another project for that long time ago... It didn't get enough love so far: https://github.com/lasconic/openapi-finary

**Comment by nmathey** [comment]
Yeah. I'll still need to spend sometime on openapi description, but is is on my ToLearn list ;)

**Comment by nmathey** [comment]
I guess we can close this issue unless I'm wrong ?
