### ISSUE TITLE
Minor finary_uapi versioning for bug fix update?

### ISSUE THREAD

**Issue by nmathey** [lasconic/finary_uapi#140]
Hi @lasconic ,

Sorry for my ignorance as I'm still learning here :)
While I'm developing an app client to finary_uapi I would liek to keep using the most updated version of it, and especially when there was some bug fixes (mine actually :p)

I think `poetry update` on my application is focusing on the dependencies version number: if not new version number = not updating.
So I guess we should have minor versioning number updated here for each PR raised/approved/merge?

For instance, finary_uapi current version = "0.1.8" should be update to version = "0.1.8.1" in order me to get the package updated localy?

As a work around for now I updated my `pyproject.toml` file with
 `finary-uapi = { git = "https://github.com/lasconic/finary_uapi.git" }`

Thanks for your help :)

**Comment by lasconic** [comment]
I need to create a workflow to publish directly to pipy from a push on main, but it's not in place yet. Your workaround is good.

**Comment by lasconic** [comment]
Let me have a look to the two last PR hopefully today and I will push a new version
