### ISSUE TITLE
Can't signing anymore ?

### ISSUE THREAD

**Issue by nmathey** [lasconic/finary_uapi#177]
Hi,

Someone reported me this issue that I'm also able to reproduce.

```
abc@82ddd3721216:~/workspace/finary_uapi$ python -m finary_uapi signin
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/config/workspace/finary_uapi/finary_uapi/__main__.py", line 452, in <module>
    sys.exit(main())
  File "/config/workspace/finary_uapi/finary_uapi/__main__.py", line 155, in main
    result = signin(args["MFA_CODE"])
  File "/config/workspace/finary_uapi/finary_uapi/signin.py", line 50, in signin
    if xjson["response"]["status"] == "complete":
KeyError: 'response'
abc@82ddd3721216:~/workspace/finary_uapi$ 
```

**Comment by lasconic** [comment]
I'll have a look asap.

**Comment by lasconic** [comment]
Mmm I can't reproduce. Do you have MFA on ?

**Comment by nmathey** [comment]
Yes I think I enabled it just recently.
I'm gonna try to remove it if you want.


Le mer. 21 févr. 2024 à 20:42, Nicolas Froment ***@***.***> a
écrit :

**Comment by lasconic** [comment]
Ok I'll add it and test.

**Comment by lasconic** [comment]
It works with 2FA as well. 
The code assumes it works. I could add more information if the second call with the 2fa code is not successful. Let me know if you find the root cause.

**Comment by nmathey** [comment]
Deactivating 2FA makes it work again.
Can you try activating it and try again signin 24h+ later (I don't how caching work)?

**Comment by nmathey** [comment]
Got multiple feedback with the same issue from diferent users.
You still not able to reproduce it?

**Comment by nmathey** [comment]
FYI: https://community.finary.com/t/mise-en-place-obligatoire-du-2fa/12549

**Comment by lasconic** [comment]
I'm sorry I can't reproduce. I have 2FA on in finary. I open Google Auth on my phone, run "signin MFA_CODE" where MFA_CODe is the code I read on my app and it works, I'm signed in.
 
The error message you see is exactly the one I get if I sign in with 2Fa activated by without the 2FA code passed to signin. Are your users aware that they need to pass the 2FA code when they sign in ?

**Comment by nmathey** [comment]
I think Finary is starting [forcing 2FA usage](https://community.finary.com/t/mise-en-place-obligatoire-du-2fa/12549) for somme user without updating the end user configuration as it deactivated on front-end but some users still experiencing the issue.
While activating the 2FA and passing the generated code through seems to work.

I have one user still having the issue but I'll ask him to force update dependencies to make sure it is not something else. He is not on github so trying to help him as much as I could.

**Comment by nmathey** [comment]
I guess we can close this issue ;)
I was able to reproduce it anymore since I forced using 2FA due that I use Crypto Finary services.
