### ISSUE TITLE
Readme to update after the change to Poetry

### ISSUE THREAD

**Issue by fdeprey** [lasconic/finary_uapi#78]
After the change "[Move from pip to poetry, rename project to finary_uapi](https://github.com/lasconic/finary_uapi/commit/21da45b5a09334c9cfde5eb4ee69a91bbe770a15)" the readme was not updated as still as to start doing `Install requirements. pip install -r requirements.txt` which does not work.

**Comment by lasconic** [comment]
Working on a CONTRIBUTING.md file. If you don't plan to contribute, you can now find the project on Pypi.  https://pypi.org/project/finary-uapi/
