### ISSUE TITLE
Get dividends

### ISSUE THREAD

**Issue by lasconic** [lasconic/finary_uapi#87]
Finary+ users can get dividend calendar. Let's search for the API endpoint and add a function.

**Comment by lasconic** [comment]
Let's start with dividends for all investments. I will add a function in `portfolio.py` called `get_portfolio_investments_dividends`

You can test it with `finary_uapi investments dividends`

**Comment by lasconic** [comment]
Done see https://github.com/lasconic/finary_uapi/pull/88

**Comment by lasconic** [comment]
Available in version 0.1.4 on pypi. Also with sharing links (but no dividend history there of course...)

**Comment by nmathey** [comment]
Gonna try this this week thanks :)
Might be a dummy question but how can we list all available endpoints from Finary API (how can we find them out?)?

**Comment by lasconic** [comment]
There are no dummy questions, right?
As far as I know, there is no public place where all the calls are listed. The only way I can think of to get most of the calls would be to record all the calls on the website (or the app) while visiting every single page. You can do that with web console of your browser. Start it, go to Network tab, filter api.finary.com, and visit as many pages as you can.


Firefox (and chrome?) let you save all the calls in HAR format. Some tools can turn HAR to OpenAPI (see https://github.com/jonluca/har-to-openapi for example), and then OpenAPI spec can be turn into API client code (something like finary_uapi, but here I did the whole work manually...) or docs. 
I have [another project](https://github.com/lasconic/openapi-finary/), currently on hold, where I started to write an OpenAPI spec by hand. I tried Har2OpenAPI but the result was not readable by a human (for example objects were not reused. Meaning all the calls using a "Currency" would define a different currency object without "factorizing")
